-- =============================================================================
-- catalogue.sql — the REAL Sky Bites catalogue, generated. E16-48.
-- =============================================================================
--
-- GENERATED BY tools/seed-catalogue/build.mjs FROM tools/seed-catalogue/data/*.csv.
-- Do not hand-edit: the next run overwrites it. Change the CSVs or the generator.
--
-- Source: the Bubble catalogue export of 2026-08-11 — dishes, prices, menus, schools,
-- kitchens and break times. NO User, Child, Order or Dish_In_Order: that is real data
-- about minors and does not go near staging. School and kitchen contact emails were
-- dropped at import rather than blanked (see the generator header).
--
-- Idempotent: every insert is `on conflict do nothing` and every id is derived from the
-- legacy Bubble id, so re-running changes nothing and all environments agree on ids.
--
-- Three things this file deliberately does NOT contain, because they would be invented:
--   * `food_type` (veg / non-veg / egg) — [DM-17] is open; guessing it in this market is a
--     trust failure, not a cosmetic gap. Admin fills it before launch.
--   * `calories_kcal` — the source gives ranges ("310-340"); the text is kept in
--     `nutrition->>'calories_text'` and the integer left null rather than made up.
--   * `dish_allergen` — never derived from an ingredients list. Tier S.
--
-- Note: excluded 1 school(s) outside Mohali: Demo School (Chandigarh).
-- Note: published 2 menus regardless of legacy status (see header note).
-- Note: merged 6 duplicate dish rows (uq_dish_kitchen_name); 4 had conflicting calorie text, preserved not resolved.
-- Note: calorie conflict: Blueberry Muffin = 400-430 vs 240–340.
-- Note: calorie conflict: Lemon Ice Tea = 90-120 vs 80–140.
-- Note: calorie conflict: Peach Ice Tea = 100-130 vs 100–160.
-- Note: calorie conflict: Cold Coffee = 160 vs 250–350.
-- All money is integer paise (non-negotiable #3). Legacy prices are whole rupees and are
-- GST-EXCLUSIVE (docs/mvp-scope.md): 5% is added at checkout, not baked in here.

begin;

-- Mohali. One city, one state, flat 5% GST as CGST 2.5% + SGST 2.5% (M2, R11).
insert into city (id, code, name, state_name, gst_state_code, country_code, timezone) values
  ('e460fc5f-0b52-4036-a9df-98ad3da886f9', 'mohali', 'SAS Nagar (Mohali)', 'Punjab', '03', 'IN', 'Asia/Kolkata')
on conflict (id) do nothing;

-- The one real kitchen. Contact columns are left null: the export had an owner email and
-- it was dropped at import rather than carried into a table anon can reach columns of.
insert into kitchen (id, code, name, city_id, address_line1, legacy_bubble_id) values
  ('35ec28ed-71df-4592-a7d0-32b62d5df354', 'sky-bites', 'Sky Bites', 'e460fc5f-0b52-4036-a9df-98ad3da886f9', 'Block-F, SAS Nagar, Sector 82, Mohali.', '1760494526791x258070929950949380')
on conflict (id) do nothing;

-- 3 real schools. Demo School (Chandigarh) is excluded: v1 is Mohali only.
-- `onboarded_at` is set from the real menu-assignment date: without it the anon policy hides
-- the school entirely and the app renders an empty picker (ux-spec §5.21).
insert into school (id, code, name, city_id, kitchen_id, institution_type, address_line1,
                     onboarded_at, legacy_bubble_id) values
  ('77308e75-d8e9-47ba-a503-7c38d482a72c', 'amity-international-school', 'Amity International School', 'e460fc5f-0b52-4036-a9df-98ad3da886f9', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'school', 'Sector 79, Mohali', '2025-10-16', '1749446685836x657725915595526160'),
  ('50994394-8557-4985-a76f-707d16a83c1a', 'paragon-senior-secondary', 'Paragon Senior Secondary', 'e460fc5f-0b52-4036-a9df-98ad3da886f9', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'school', 'Paragon Senior Secondary School Sector 71', '2026-05-22', '1779448510870x587104545013734000'),
  ('79752fe3-841f-45b6-a47b-1169ce70e648', 'gem-public-school', 'Gem Public School', 'e460fc5f-0b52-4036-a9df-98ad3da886f9', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'school', 'Phase-3B2 , Behind Hanuman Mandir', '2025-10-16', '1779448571787x588549078749398100')
on conflict (id) do update set
  onboarded_at = coalesce(school.onboarded_at, excluded.onboarded_at),
  is_active    = true,
  updated_at   = now();

-- Break times, exactly as exported. Only Amity has any in the source; the other schools
-- get none rather than a plausible invention — an unresolved break renders as "confirmed
-- with the kitchen" (ux-spec §5.4) rather than as a time nobody agreed to.
insert into break_time (id, school_id, code, label, starts_at, ends_at, sort_order, legacy_option_value) values
  ('06ca8ef9-d342-4596-aae1-08f43f7f3a55', '77308e75-d8e9-47ba-a503-7c38d482a72c', 'break-1', '10:40AM - 11:15AM', '10:40:00', '11:15:00', 10, '10:40AM - 11:15AM'),
  ('5659c6ab-6598-40ee-a563-04d688baaf64', '77308e75-d8e9-47ba-a503-7c38d482a72c', 'break-2', '11:15AM - 11:40AM', '11:15:00', '11:40:00', 20, '11:15AM - 11:40AM')
on conflict (id) do nothing;

-- 8 real categories, in the order the menu screen groups by.
insert into dish_category (id, code, display_name, sort_order) values
  ('77f2d769-6bfa-428b-a0f5-b7a93ee4016c', 'bakery', 'Bakery', 10),
  ('45b86cf1-3d03-454f-ac37-66105565da67', 'breakfast', 'Breakfast', 20),
  ('8b34bbfb-c4eb-4485-a432-6c996d6d0116', 'continental', 'Continental', 30),
  ('d8e07c8c-2947-4bd0-a3fe-636b32409eb1', 'drinks', 'Drinks', 40),
  ('8b5c179f-18b7-4b30-af16-e886715d7aaf', 'meals', 'Meals', 50),
  ('ce3e2810-b49d-45e5-a189-adaaba740a8d', 'quick-bites', 'Quick Bites', 60),
  ('3e0c0173-20fd-4900-a664-2e975f25eac2', 'salads', 'Salads', 70),
  ('e30379a0-1a89-41f4-afcd-4ff007bb7794', 'sandwich', 'Sandwich', 80)
on conflict (id) do nothing;

-- 79 real dishes. food_type null by design ([DM-17]); calories kept as text in
-- `nutrition` because the source gives ranges and a midpoint would be a number nobody measured.
insert into dish (id, kitchen_id, name, description, ingredients_text, calories_kcal,
                  nutrition, category_id, food_type, legacy_bubble_id) values
  ('9ba5f4bb-ee85-49e8-a296-af9ec05a0477', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Wheat Jaggery Cake', 'Wheat Jaggery Cake – A soft, wholesome cake made with wheat flour and sweetened naturally with jaggery—earthy, comforting, and guilt-free indulgence.', 'Ashirwad Atta, Jaggery, Curd, Baking Soda, Refined Soybean Oil', null, '{"calories_text":"310-340"}'::jsonb, '77f2d769-6bfa-428b-a0f5-b7a93ee4016c', null, '1751068956804x158696559691264600'),
  ('81a95eaa-ec46-4ba2-ad37-fecd9484247a', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'French Butter Croissant', 'French Butter Croissant – Light, flaky, and golden with a rich buttery aroma—perfectly crisp outside and soft within.', 'Maida, Brown Sugar, Salt, Gluten, Improver, Cow Butter, Fresh Cream, Fresh Yeast', null, '{"calories_text":"330-370"}'::jsonb, '77f2d769-6bfa-428b-a0f5-b7a93ee4016c', null, '1751068956804x307346726140140600'),
  ('df802cb2-ddf9-4fad-aeb0-76ae8ddb58cb', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Pain Au Chocolat', 'Pain au Chocolat – A delicate pastry made with layers of buttery dough and rich dark chocolate, lightly sweetened with brown sugar and baked to golden perfection—a French classic with a melt-in-your-mouth finish.', 'Maida, Brown Sugar, Dark Chocolate, Salt, Gluten, Improver, Cow Butter, Fresh Cream, Fresh Yeast', null, '{"calories_text":"430-460"}'::jsonb, '77f2d769-6bfa-428b-a0f5-b7a93ee4016c', null, '1751068956804x656330743180066700'),
  ('476554f2-e6f4-4d5a-a69d-039461bc5751', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Carrot And Raisin Cake', 'Carrot & Raisin Cake – Moist and gently spiced, this wholesome cake is packed with sweet carrots and juicy raisins—comforting, flavourful, and naturally delicious.', 'Fresh Grated Carrot, Curd, Brown Sugar, Refined Soybean Oil, Maida, Baking Soda', null, '{"calories_text":"290-320"}'::jsonb, '77f2d769-6bfa-428b-a0f5-b7a93ee4016c', null, '1751068956804x820523134006956500'),
  ('52d91c2f-c1be-4147-a7ff-f061a11213b2', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Tomato, Cucumber Cheese Sandwich In Brown Bread', 'Fresh Veggie & Cheese Sandwich – Crisp tomato and cucumber layered with creamy mayo, a slice of cheese, and a dash of salt and pepper—simple, fresh, and full of flavour.', 'Fresh Tomato, Cucumber, Mayonnaise, Cheese Slice, Salt, Pepper', null, '{"calories_text":"420-440"}'::jsonb, 'e30379a0-1a89-41f4-afcd-4ff007bb7794', null, '1751068956805x153486284508529860'),
  ('d069659d-baac-4e9b-a06a-be91ce21dac9', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Paneer Tikka Sandwich In Focaccia Bread', 'Paneer Tikka Sandwich – Smoky paneer tikka layered with crisp lettuce, onions, and creamy mayo, seasoned with paprika and salt—all packed into toasted bread for a bold, flavourful bite.', 'Paneer Tikka, Mayonnaise, Paprika Powder, Salt, Onion, Lettuce', null, '{"calories_text":"420-500"}'::jsonb, 'e30379a0-1a89-41f4-afcd-4ff007bb7794', null, '1751068956805x155143217195583100'),
  ('a77dbdae-cc3a-46fc-a924-aca59b590410', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Brown Wheat Brownie With Choco Sauce', 'Brown Wheat Brownie with Choco Sauce – A rich, fudgy brownie made with wholesome wheat flour, drizzled generously with smooth chocolate sauce—indulgence meets goodness in every bite.', 'Atta, Sugar, Dark Chocolate, Cocoa Powder, Butter', null, '{"calories_text":"450-480"}'::jsonb, '77f2d769-6bfa-428b-a0f5-b7a93ee4016c', null, '1751068956805x173763608008315600'),
  ('0ea897ef-9bde-45d4-a167-f442bc80e68e', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Veg Sandwich In Brown Bread', 'Veg Sandwich (Brown Bread) – A hearty brown bread sandwich filled with sautéed capsicum, corn, broccoli, creamy mayo, melted cheese, and a dash of oregano, salt, and pepper—wholesome, flavourful, and satisfying.', 'Capsicum, Corn, Broccoli, Mayo, Cheese Slice, Oregano Mix, Salt, Pepper', null, '{"calories_text":"270-350"}'::jsonb, 'e30379a0-1a89-41f4-afcd-4ff007bb7794', null, '1751068956805x388091610578040500'),
  ('ff30cec3-1de8-4575-a351-50a76668bc81', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Blueberry Muffin', 'Blueberry Muffin – Soft, fluffy muffin bursting with juicy blueberries—lightly sweet, perfectly baked, and a delightful treat any time of day.', 'Flour (Maida), Sugar, Baking Powder, Baking Soda, Refined Soybean Oil, Blueberry Filling', null, '{"calories_text":"400-430","calories_text_conflicting":"240–340"}'::jsonb, '77f2d769-6bfa-428b-a0f5-b7a93ee4016c', null, '1751068956805x636647856382776400'),
  ('f97f39b1-ded3-481c-a1ae-885091984541', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Choco Muffin', 'Choco Muffin – Rich, moist chocolate muffin with melty choco chips in every bite—deeply satisfying and perfect for chocolate lovers.', 'Flour (Maida), Sugar, Baking Powder, Baking Soda, Refined Soybean Oil, Dark Chocolate', null, '{"calories_text":"410-440"}'::jsonb, '77f2d769-6bfa-428b-a0f5-b7a93ee4016c', null, '1751068956805x764116958381420700'),
  ('54b0a3b7-a96f-44cb-a6fc-1765fbca9ed9', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Bagels With Cream Cheese', 'Bagel with Cream Cheese – A toasted, bagel generously spread with smooth, tangy cream cheese—simple, classic, and deliciously satisfying.', 'Maida Base Bread, Tomato, Cucumber, Cream Cheese, Salt, Pepper, Mayonnaise', null, '{"calories_text":"400-430"}'::jsonb, 'e30379a0-1a89-41f4-afcd-4ff007bb7794', null, '1751068956808x434891866366537540'),
  ('c02315fc-27f6-41b7-a755-16ab521db373', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Veg Chilly Puff (Maida)', 'Veg Chilli Puff – Flaky, golden pastry filled with a savoury mix of spiced vegetables—crisp outside, warm and delicious inside.', 'Maida, Salt, Margarine, Butter (Potato Filling)', null, '{"calories_text":"300-350"}'::jsonb, 'ce3e2810-b49d-45e5-a189-adaaba740a8d', null, '1751068956809x201360143180394180'),
  ('64f15f33-361b-451c-a4ed-4179735662a3', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Aloo & Pea Tikki Cheese Burger (Wheat Burger)', 'Aloo & Pea Tikki Cheese Burger (Wheat Burger) – A wholesome burger made with a crispy aloo-pea patty, melted cheese, fresh veggies, and sauces, all tucked into a soft whole wheat bun—flavourful and filling with every bite.', 'Potato, Green Peas, Corn Flour, Bread Crumb, Salt, Pepper, Oregano Mix, Cheese', null, '{"calories_text":"350-450"}'::jsonb, 'ce3e2810-b49d-45e5-a189-adaaba740a8d', null, '1751068956809x556265520042649150'),
  ('ca24ff5a-f35a-4136-a58d-ed0b2d185578', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Boiled Egg Mix In Brown Wheat Multigrain Sub Sandwich', 'Boiled Egg Mix in Brown Wheat Multigrain Sub – A nutritious and tasty sub loaded with seasoned boiled egg mix, crisp veggies, and light mayo, all tucked in a hearty multigrain wheat roll—wholesome and satisfying with every bite.', 'Boiled Egg, Cucumber, Parsley, Mayonnaise, Salt, Pepper', null, '{"calories_text":"350-420"}'::jsonb, 'e30379a0-1a89-41f4-afcd-4ff007bb7794', null, '1751068956809x565964505118322900'),
  ('c59857ba-c2c0-4dfb-a9e1-a471c6eb621a', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Paneer Jalferzi Wrap (Atta Wrap)', 'Paneer Jalfrezi Wrap – Spicy paneer strips stir-fried with peppers, onions, and tangy masala, wrapped in a soft whole wheat roti—bold, vibrant, and full of flavour.', 'Tortilla Wrap, Paneer, Capsicum, Tomato, Onion, Fresh Coriander, Spices', null, '{"calories_text":"495"}'::jsonb, 'ce3e2810-b49d-45e5-a189-adaaba740a8d', null, '1751068956809x629236588467374500'),
  ('6e290412-f98a-4fa9-a55b-c4123a2ede4a', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Paneer Croissant (Maida Base)', 'Paneer Croissant – A buttery, flaky croissant filled with spiced paneer and herbs—warm, indulgent, and packed with desi flavour in every bite.', 'Paneer Tikka, Mayonnaise, Paprika Powder, Salt, Onion, Cheese Spread', null, '{"calories_text":"450-530"}'::jsonb, 'e30379a0-1a89-41f4-afcd-4ff007bb7794', null, '1751068956809x795650377231993400'),
  ('8f4e81fe-14f4-4405-ab76-401f251680f1', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Cheese Garlic Bread (Maida Bread)', 'Cheese Garlic Bread – Crisp on the edges, soft inside, and loaded with melted cheese and aromatic garlic—an irresistible savoury treat.', 'Mozzarella Cheese, Garlic, Butter, Chilli Flakes, Oregano Mix', null, '{"calories_text":"400-420"}'::jsonb, 'ce3e2810-b49d-45e5-a189-adaaba740a8d', null, '1751068956809x796477323085994200'),
  ('56aba5d0-d635-4ca5-a7e7-6ae90e8c4f83', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Mushroom Croissant (Maida Base)', 'Mushroom Croissant – A buttery, flaky croissant filled with creamy sautéed mushrooms and herbs—rich, savoury, and perfectly indulgent.', 'Mushroom, Cream, Butter, Onion, Garlic, Cheese Spread, Parsley', null, '{"calories_text":"470-500"}'::jsonb, 'e30379a0-1a89-41f4-afcd-4ff007bb7794', null, '1751068956809x907509860918670500'),
  ('e6c7b983-711a-42c7-a6c1-f8c074688bd9', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Vada Pao (Atta Base Bread)', 'Vada Pav – Mumbai’s iconic street food—spicy potato fritter tucked in a soft pav bun, layered with chutneys and fried green chilli for that perfect desi bite.', 'Potato, Turmeric, Chili Powder, Curry Leaves, Fresh Coriander, Mustard Seed, Oil', null, '{"calories_text":"300-350"}'::jsonb, 'ce3e2810-b49d-45e5-a189-adaaba740a8d', null, '1751068956809x950160930414243100'),
  ('be429d49-67dd-40e9-a709-65e3107172c5', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Mexican Style Veg Filling Wrap (Atta Wrap)', 'Mexican Style Veg Wrap – A bold, zesty mix of sautéed veggies, beans, salsa, and cheese rolled in a soft tortilla—flavour-packed and perfect on the go.', 'Tortilla Wrap, Paneer, Capsicum, Corn, Cheese, Tomato, Onion, Fresh Coriander, Spices', null, '{"calories_text":"350-450"}'::jsonb, 'ce3e2810-b49d-45e5-a189-adaaba740a8d', null, '1751068956810x202618328802040000'),
  ('9275cef8-840d-41a5-afc1-f321f5688a93', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Veg Manchurian With Fried Rice', 'Veg Manchurian with Rice – Crispy vegetable balls tossed in a spicy Indo-Chinese sauce, served with fragrant fried rice for a flavour-packed, satisfying meal.', null, null, '{"calories_text":"580-620"}'::jsonb, '8b5c179f-18b7-4b30-af16-e886715d7aaf', null, '1751068956811x329156539650981000'),
  ('9ecbfe93-cbd0-4c22-a3e3-2c2334a311ac', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Rajma With Rice Or Prantha', 'Rajma with Rice or Parantha – Comforting and hearty kidney beans slow-cooked in spiced tomato gravy, served with fluffy rice or warm parantha for a wholesome North Indian classic.', null, null, '{"calories_text":"450-480"}'::jsonb, '8b5c179f-18b7-4b30-af16-e886715d7aaf', null, '1751068956811x458739705102099840'),
  ('0889579a-1729-47d8-af98-6dfee108c886', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Fried Rice With Exotic Veg', 'Veg Fried Rice – Fluffy rice stir-fried with colourful veggies, soy sauce, and spices—a delicious, wholesome Indo-Chinese favourite.', null, null, '{"calories_text":"510-530"}'::jsonb, '8b5c179f-18b7-4b30-af16-e886715d7aaf', null, '1751068956811x610991847600959000'),
  ('749f188d-5fef-4e82-a587-4e023eda7720', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Egg Roll (Atta Wrap)', 'Egg Roll – A soft roti wrapped around a flavourful egg filling, fresh veggies, and tangy sauces—perfectly spiced and easy to grab on the go.', 'Egg Omelette With Veggies With Mayo Sauce In Brown Wrap', null, '{"calories_text":"300-320"}'::jsonb, 'ce3e2810-b49d-45e5-a189-adaaba740a8d', null, '1751068956811x660338023605968600'),
  ('92f3aebb-db75-428c-abb0-603faa0e4e60', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Paneer Gravy With Rice /Wheat Prantha', 'Paneer Gravy with Rice or Parantha – Soft paneer cubes simmered in a rich, spiced tomato-based gravy, served with fluffy rice or warm parantha for a comforting and satisfying meal.', null, null, '{"calories_text":"500-570"}'::jsonb, '8b5c179f-18b7-4b30-af16-e886715d7aaf', null, '1751068956811x689699990859977200'),
  ('71680f45-adba-4b5e-a60a-7c2b8e6ee844', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Dal Makhni With Rice/Wheat Prantha', 'Dal Makhani with Rice or Parantha – Slow-cooked black lentils in a creamy, buttery gravy served with soft rice or warm parantha—rich, comforting, and full of flavour.', null, null, '{"calories_text":"500-550"}'::jsonb, '8b5c179f-18b7-4b30-af16-e886715d7aaf', null, '1751068956811x899033102354014100'),
  ('f4853989-b2a7-4841-a517-a99bd5bf7b2d', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Chole Masala With Rice /Wheat Prantha /Wheat Atta Kulcha', 'Chole Masala with Rice, Wheat Parantha or Kulcha – Spicy, tangy chickpeas cooked in a rich, aromatic gravy served with your choice of fluffy rice, crispy wheat parantha, or soft kulcha—a North Indian favourite that never fails to satisfy.', null, null, '{"calories_text":"500-570"}'::jsonb, '8b5c179f-18b7-4b30-af16-e886715d7aaf', null, '1751068956811x959695653570769400'),
  ('257bfaf0-1ad1-4edb-a1bf-cc1a67a0d355', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Corn And Mix Pepper Salad', 'Corn & Mixed Pepper Salad – A crunchy, colourful mix of sweet corn and bell peppers—fresh, juicy, and full of flavour in every bite.', 'Corn, Mix Capsicum, Mayo, Mustard, Parsley, Salt, Pepper', null, '{"calories_text":"186"}'::jsonb, '3e0c0173-20fd-4900-a664-2e975f25eac2', null, '1751068956812x480724353239390100'),
  ('67c4c96a-4ed0-42e3-a801-1a073edff543', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Bhel Puri Salad', 'Bhelpuri – A crunchy, tangy street-style snack made with puffed rice, sev, chutneys, and fresh veggies—bursting with flavour in every bite.', 'Bhel, Onion, Tomato, Green Chutney, Saunf Chutney', null, '{"calories_text":"180"}'::jsonb, '3e0c0173-20fd-4900-a664-2e975f25eac2', null, '1751068956812x783511747475615000'),
  ('bef50ee7-e9b3-4702-a1d2-760447dae14a', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Aloo Channa Chat (White And Black Channa)', 'Aloo Chana Chaat – A zesty mix of boiled potatoes and chickpeas tossed with spices, chutneys, and fresh herbs—tangy, hearty, and full of flavour.', 'White And Black Channa, Onion, Tomato, Mix Spice, Green Chutney, Tomato Sauce', null, '{"calories_text":"260"}'::jsonb, '3e0c0173-20fd-4900-a664-2e975f25eac2', null, '1751068956812x785709064418025300'),
  ('077a8845-034f-4fe4-ac88-7bbd1d3099bb', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Banana And Honey Shake', 'Banana Honey Shake – Smooth, naturally sweet, and packed with goodness—perfect for a tasty energy boost.', 'Banana, Milk, Sugar, Ice', null, '{"calories_text":"300"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1751068956813x101483837751406690'),
  ('e91ffde9-99ef-4ef6-a8ce-d0035570bbc3', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Mango Shake (Seasonal)', 'Mango Shake – Thick, juicy, and irresistibly sweet—summer’s favourite fruit in every sip.', null, null, '{"calories_text":"180-220"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1751068956813x251651141909131170'),
  ('4a1b9612-c426-49f4-a415-eac8b12ad18a', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Three Beans Salad', '3 Bean Salad – A colourful, protein-rich mix of kidney beans, chickpeas, and green beans tossed in a light, tangy dressing—fresh, filling, and full of flavour.', 'Beans, Fresh Tomato, Onion, Cucumber, Lemon, Coriander, Salt, Pepper', null, '{"calories_text":"106"}'::jsonb, '3e0c0173-20fd-4900-a664-2e975f25eac2', null, '1751068956813x468595151498087500'),
  ('ea6c7701-47e3-49e8-a287-130101806649', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Quinoa Salad', 'Quinoa Salad – Light, wholesome, and refreshing—fluffy quinoa mixed with crisp veggies and a zesty dressing for a perfect healthy bite.', 'Boiled Quinoa, Cucumber, Tomato, Coriander, Lemon, Salt, Pepper', null, null, '3e0c0173-20fd-4900-a664-2e975f25eac2', null, '1751068956813x569682156705211260'),
  ('c75aedc4-c422-4f03-aa89-eeba3c5ff187', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Hot Choco Milk', 'Hot Chocolate Milk – Warm, smooth, and chocolatey—comfort in a cup for all ages.', null, null, '{"calories_text":"220-280"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1751068956813x621942374217471900'),
  ('f7ed2183-8f9e-466b-aa7c-ada3b3512793', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Fruit Salad', 'Fruit Salad – A colourful medley of fresh, juicy fruits—naturally sweet, refreshing, and full of goodness.', 'Seasonal Fruit', null, '{"calories_text":"110"}'::jsonb, '3e0c0173-20fd-4900-a664-2e975f25eac2', null, '1751068956813x664916371811283800'),
  ('7ff727e6-75e9-419a-a40c-1496a3f53b97', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Lemon Ice Tea', 'Lemon Iced Tea – Cool, citrusy, and refreshing—perfect for a quick sip between busy school hours.', 'Tea, lemon, sugar, ice', null, '{"calories_text":"90-120","calories_text_conflicting":"80–140"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1751068956814x489412216784268000'),
  ('7b6a9487-a8c8-4313-ab59-4775e33b67e1', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Lemonade', 'Lemonade – Zesty, sweet, and super refreshing—a classic thirst-quencher for any time of day.', null, null, '{"calories_text":"109"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1751068956814x819085531963631900'),
  ('bd743b4e-99ea-4858-a879-cf359e3abf9a', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Strawberry Shake (Seasonal)', 'Strawberry Shake – Creamy, fruity, and fun—blended with love for a sweet burst of strawberry delight.', 'Fresh strawberries or strawberry puree, Chilled milk, Vanilla ice cream (optional for creaminess), Sugar, Ice cubes', null, '{"calories_text":"150-200"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1751068956814x870381594421953900'),
  ('1ecb1eb0-a3e3-4605-a10c-319356fefa2c', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Peach Ice Tea', 'Peach Iced Tea – Smooth, fruity, and chilled—peachy goodness in every sip.', 'Black tea, Peach syrup/puree, Lemon juice, Sugar, Cold water, Ice cubes', null, '{"calories_text":"100-130","calories_text_conflicting":"100–160"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1751068956814x900098835367759000'),
  ('6a355b36-8c19-4dd7-ae33-038cf14b0f49', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Hot Coffee', 'Hot Coffee,  a mouthwatering favorite crafted to delight your senses!', null, null, '{"calories_text":"135"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1751068957564x483261028215033340'),
  ('e8da2b16-eed3-4010-af17-f67219a3d87e', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Tea', 'A steaming cup of Indian tea — bold, spiced, and soul-warming — where every sip awakens your senses and comforts your spirit.', null, null, '{"calories_text":"130"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1751068957564x545175872992901500'),
  ('7135dbf4-2182-4ed6-ae6a-2f9afee2c0d3', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Cold Coffee', 'Cold Coffee – Chilled, creamy, and lightly sweet—your perfect pick-me-up on a warm day.', 'Coffee, milk, sugar, ice', null, '{"calories_text":"160","calories_text_conflicting":"250–350"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1751068957564x640273735166589400'),
  ('f2450d69-4bf9-41cc-a489-079b55e619f6', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Masala Corn', 'Masala Corn delightfully made with Steamed Corn, and spices. It''s a bite of happiness.', 'Steamed Corn, Chat Masala, Butter', null, null, '3e0c0173-20fd-4900-a664-2e975f25eac2', null, '1751068957565x156602631589117800'),
  ('a2d66075-8a26-44a7-a23e-115287123af7', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Brown Wheat Pasta With Veg And Tomato Sauce', 'Brown Wheat Pasta With Veg And Tomato Sauce delightfully made with Boiled Pasta, it''s a bite of happiness.', 'Boiled Pasta, Tomato Sauce, Veggies, Cheese', null, '{"calories_text":"330-380"}'::jsonb, '8b34bbfb-c4eb-4485-a432-6c996d6d0116', null, '1751068957565x370002508235305800'),
  ('082891cf-f1a4-4fbb-aefb-07d0f8f817f1', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Brown Wheat Pasta With Mushroom And Pesto Cream Sauce', 'Brown Wheat Pasta With Mushroom And Pesto Cream Sauce.  The magic begins with Boiled Pasta and ends in satisfaction.', 'Boiled Pasta, Tomato Sauce, Cheese, White Sauce, Mushroom, Seasoning Mix', null, '{"calories_text":"480-550"}'::jsonb, '8b34bbfb-c4eb-4485-a432-6c996d6d0116', null, '1751068957565x375934141297079360'),
  ('3c7fc0ce-c798-4b36-a4a2-b778db302c68', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Butter Corn', 'Butter Corn,  steamed corn with butter, salt and seasonings.', 'Steamed Corn, Butter', null, null, '3e0c0173-20fd-4900-a664-2e975f25eac2', null, '1751068957565x800981728189924500'),
  ('b71f4b14-ec16-4675-a2ea-70880c6a3fa4', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Omelette w Toast', 'Egg omelette served with toasted bread', 'Eggs, onion, tomato, spices, bread, butter', null, '{"calories_text":"~320"}'::jsonb, '45b86cf1-3d03-454f-ac37-66105565da67', null, '1779449140805x388231208917267000'),
  ('78977f3f-7be5-4902-aa29-196daecd9e78', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Boiled Eggs (3 pcs)', 'Simple boiled eggs served whole', 'Eggs, salt', null, '{"calories_text":"~210"}'::jsonb, '45b86cf1-3d03-454f-ac37-66105565da67', null, '1779449140805x998293772833065500'),
  ('ca4c954e-c784-4484-a764-dd91d85921e6', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Idli Sambar', 'Steamed rice cakes with lentil soup', 'Rice, urad dal, sambar dal, vegetables, spices', null, '{"calories_text":"~280"}'::jsonb, '45b86cf1-3d03-454f-ac37-66105565da67', null, '1779449140806x193032194737593700'),
  ('249d5eea-bb21-4555-ab1a-9fb74911a4cf', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'French Toast with Choco Syrup', 'Sweet fried bread with chocolate syrup', 'Bread, eggs, milk, sugar, chocolate syrup', null, '{"calories_text":"~420"}'::jsonb, '45b86cf1-3d03-454f-ac37-66105565da67', null, '1779449140806x206081468704266900'),
  ('3118e713-773c-4201-a5e1-826edaf788bf', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Mix Veg Poha', 'Flattened rice cooked with vegetables and spices', 'Poha, peas, carrot, onion, turmeric, curry leaves', null, '{"calories_text":"~300"}'::jsonb, '45b86cf1-3d03-454f-ac37-66105565da67', null, '1779449140806x346491320241788740'),
  ('5ff51909-1a40-4e86-a006-eb57160a78f2', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Stuffed Paratha', 'Indian flatbread stuffed with filling', 'Wheat flour, potato/paneer, spices, oil', null, '{"calories_text":"~400"}'::jsonb, '45b86cf1-3d03-454f-ac37-66105565da67', null, '1779449140806x422240165857332740'),
  ('8b4d2880-9d4a-425c-a350-84d13e3e5a7a', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Pancakes w Honey', 'Soft pancakes topped with honey', 'Flour, milk, eggs, sugar, honey', null, '{"calories_text":"~380"}'::jsonb, '45b86cf1-3d03-454f-ac37-66105565da67', null, '1779449140806x477366637079625000'),
  ('feeef41f-7f46-4f82-aedb-03d2f5da9b28', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Scrambled Egg w Toast', 'Soft scrambled eggs with toasted bread', 'Eggs, milk, butter, bread', null, '{"calories_text":"~350"}'::jsonb, '45b86cf1-3d03-454f-ac37-66105565da67', null, '1779449140806x709927428863947400'),
  ('5886a511-7755-4077-a18d-61a913825080', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Veggie Wrap', 'Mixed vegetables wrapped in flatbread', 'Roti, lettuce, cucumber, carrot, sauces', null, '{"calories_text":"~320"}'::jsonb, 'ce3e2810-b49d-45e5-a189-adaaba740a8d', null, '1779449140807x283731477430231740'),
  ('5545b7fa-ebc5-4b08-abc0-766b459b9407', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Paneer Wrap', 'Flatbread rolled with spiced paneer', 'Tortilla/roti, paneer, veggies, sauces', null, '{"calories_text":"~450"}'::jsonb, 'ce3e2810-b49d-45e5-a189-adaaba740a8d', null, '1779449140807x884156469936501300'),
  ('18cb9677-0f79-452a-a267-37955597979b', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Mixed Fruits', 'Fresh seasonal fruit platter served chilled.', 'Banana, apple, orange', null, '{"calories_text":"120–180"}'::jsonb, 'ce3e2810-b49d-45e5-a189-adaaba740a8d', null, '1779449140808x206833398330332540'),
  ('34e0b082-3d7f-4f6b-aca7-a9506b786feb', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Sprouts', 'Fresh sprouted legumes salad', 'Moong sprouts, onion, tomato, lemon, salt', null, '{"calories_text":"~180"}'::jsonb, '3e0c0173-20fd-4900-a664-2e975f25eac2', null, '1779449140808x834907511420349700'),
  ('4fe69c9a-cc1d-4c70-a682-6ccf740f2c3a', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Corn and Cheese Puff', 'Flaky puff pastry filled with corn and cheese.', 'Puff pastry, cheese, corn', null, '{"calories_text":"320–400"}'::jsonb, '77f2d769-6bfa-428b-a0f5-b7a93ee4016c', null, '1779449140809x220913038397098080'),
  ('630bd35a-da35-483a-ab12-69164b9fe84f', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Veg and Cheese Sandwich', 'Vegetable sandwich topped with melted cheese.', 'Bread, vegetables, cheese, butter', null, '{"calories_text":"360–450"}'::jsonb, 'e30379a0-1a89-41f4-afcd-4ff007bb7794', null, '1779449140809x406105864955550500'),
  ('fc9fc49f-4f0f-4a25-a86f-b8e2c8932407', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Corn and Pepper Sandwich', 'Sweet corn and pepper filling in toasted bread.', 'Bread, corn, capsicum, cheese', null, '{"calories_text":"340–420"}'::jsonb, 'e30379a0-1a89-41f4-afcd-4ff007bb7794', null, '1779449140809x456924985028412900'),
  ('07dac96a-2696-4bb1-a58b-0267dad3a20f', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Paneer Puff', 'Crispy puff pastry stuffed with spicy paneer filling.', 'Puff pastry, paneer, spices', null, '{"calories_text":"300–380"}'::jsonb, '77f2d769-6bfa-428b-a0f5-b7a93ee4016c', null, '1779449140809x494690560453747900'),
  ('55f3fbad-f01f-42c8-a17f-e9e28341f10b', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Egg Sandwich', 'Delicious egg filling layered between toasted bread slices.', 'Eggs, bread, mayonnaise, butter', null, '{"calories_text":"350–430"}'::jsonb, 'e30379a0-1a89-41f4-afcd-4ff007bb7794', null, '1779449140809x655270608909390200'),
  ('fcf5f7ef-4ba2-4fb3-adcd-6e5aa9856a6c', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Paneer Sandwich', 'Grilled sandwich stuffed with flavorful paneer filling.', 'Bread, paneer, vegetables, butter', null, '{"calories_text":"380–450"}'::jsonb, 'e30379a0-1a89-41f4-afcd-4ff007bb7794', null, '1779449140809x908188532520013700'),
  ('a3c2e5cf-0c02-4fa1-a033-df385ea00c2e', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Chana Rice', 'Spiced chickpea curry served with steamed rice.', 'Chickpeas, rice, onion, tomato gravy', null, '{"calories_text":"450–550"}'::jsonb, '8b5c179f-18b7-4b30-af16-e886715d7aaf', null, '1779449140810x731494902361811600'),
  ('09456bbd-a4af-4745-a4b7-0e8372dc4a18', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Quinoa Khichdi', 'Healthy quinoa-based khichdi cooked with lentils and vegetables.', 'Quinoa, lentils, vegetables, spices', null, '{"calories_text":"350–450"}'::jsonb, '8b5c179f-18b7-4b30-af16-e886715d7aaf', null, '1779449140810x752114686422033400'),
  ('4d2e14b8-9672-4a9d-a1ee-a2c07d6e5213', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Rajma Rice', 'Traditional rajma curry paired with rice.', 'Kidney beans, rice, tomato gravy', null, '{"calories_text":"480–580"}'::jsonb, '8b5c179f-18b7-4b30-af16-e886715d7aaf', null, '1779449140810x961113269333929200'),
  ('2bcc8895-c2e7-4adf-a8fe-428981089cd5', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Hot Chocolate Chocolate', 'Warm and comforting hot chocolate drink.', 'Cocoa powder, milk, sugar', null, '{"calories_text":"300–420"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1779449140811x318146422163813950'),
  ('5786123a-6435-4f32-a199-c966998b3c10', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Fried Rice with Manchurian', 'Indo-Chinese fried rice served with Manchurian balls.', 'Rice, vegetables, soy sauce, Manchurian', null, '{"calories_text":"550–700"}'::jsonb, '8b5c179f-18b7-4b30-af16-e886715d7aaf', null, '1779449140811x374358487804802750'),
  ('51115c58-7fe3-4aba-a1a1-5a24d85382f5', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Banana Shake', 'Thick and creamy banana flavored milkshake.', 'Banana, milk, sugar, ice cream', null, '{"calories_text":"300–420"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1779449140811x569879533872676740'),
  ('032ffa71-416f-410d-afa4-f0c2c851a37d', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Brownie Shake', 'Rich chocolate brownie blended into a creamy shake.', 'Brownie, milk, chocolate ice cream', null, '{"calories_text":"500–650"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1779449140812x575803748111743040'),
  ('974feb0c-0649-4a60-a05f-fe36afa40e70', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Mango Shake', 'Thick mango milkshake made with fresh mangoes.', 'Mango, milk, sugar, ice cream', null, '{"calories_text":"320–450"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1779449140812x650563047183700700'),
  ('a2da0e85-574c-4846-ac0a-2bb994f4996c', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Oreo Shake', 'Creamy milkshake blended with Oreo cookies.', 'Oreo cookies, milk, ice cream', null, '{"calories_text":"450–600"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1779449140812x753190154787433700'),
  ('1b285863-ae69-4bcf-af8d-7a8544e037e3', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Veg Hot Dog', 'Soft bun stuffed with veggie filling and sauces.', 'Hot dog bun, veggie patty, sauces', null, '{"calories_text":"350–450"}'::jsonb, 'ce3e2810-b49d-45e5-a189-adaaba740a8d', null, '1779449140813x257214124201923230'),
  ('48e45752-9ad2-4630-a15a-a133a30babee', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Chocolate Doughnut', 'Soft doughnut coated with rich chocolate glaze.', 'Flour, cocoa, milk, sugar', null, '{"calories_text":"280–380"}'::jsonb, '77f2d769-6bfa-428b-a0f5-b7a93ee4016c', null, '1779449140813x265442094742111900'),
  ('59c2310c-849f-42b1-a817-8715116d8f17', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Chocolate Muffin', 'Moist chocolate flavored muffin.', 'Flour, cocoa powder, milk, eggs', null, '{"calories_text":"250–350"}'::jsonb, '77f2d769-6bfa-428b-a0f5-b7a93ee4016c', null, '1779449140813x342013160528765760'),
  ('d8552969-86e3-4166-a484-d67314744c9d', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Eggless Brownie', 'Rich and fudgy eggless chocolate brownie.', 'Flour, cocoa powder, butter, chocolate', null, '{"calories_text":"320–420"}'::jsonb, '77f2d769-6bfa-428b-a0f5-b7a93ee4016c', null, '1779449140813x687006561270116600'),
  ('a6cbc529-c379-4d80-a38b-30ea4fe43c6f', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Strawberry Shake', 'Sweet and creamy strawberry flavored shake.', 'Strawberries, milk, sugar, ice', null, '{"calories_text":"320–450"}'::jsonb, 'd8e07c8c-2947-4bd0-a3fe-636b32409eb1', null, '1779449140813x858431197571919200')
on conflict (id) do nothing;

-- 2 menus that actually carry items. Seeded 'active' regardless of the
-- legacy `status`: see the generator header — Bubble gates visibility on School-Menu.is_current,
-- not on this column, and copying it literally would seed every school an empty menu.
insert into menu (id, kitchen_id, name, status, version, published_at, legacy_bubble_id) values
  ('2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'Sky Bites - Amity', 'active', 1, now(), '1760597700442x324348174706838840'),
  ('098e2390-9b9a-46cd-ae5b-09053780d099', '35ec28ed-71df-4592-a7d0-32b62d5df354', 'School Menu - May 2026', 'active', 1, now(), '1760739730191x116059324924543180')
on conflict (id) do nothing;

-- 83 real prices. Whole rupees in the source; x100 into integer paise here.
-- GST-EXCLUSIVE — 5% is added at checkout, exactly as the Bubble cart does.
--
-- SEEDED INACTIVE — `E16-53`. This is not a style choice and it is not optional.
--
-- `0059`'s `assert_dish_is_marked` refuses any ACTIVE menu_item whose dish has no
-- `food_type`, and this file ships every dish unmarked because `[DM-17]` is open and the
-- generator will not invent a fact about food. Both are right. Together they meant this
-- seed could not be applied to a fresh database AT ALL — it died on the first row, so a
-- rebuilt staging, a new environment and E01-17's restore drill all failed at the seed.
--
-- `is_active = false` satisfies both: the rows exist and are priced, and nothing unmarked
-- is OFFERED to a parent, which is precisely what the guard is for. Marking the dishes is
-- what activates them — see the note this file prints at the end.
insert into menu_item (id, menu_id, dish_id, price_paise, sort_order, is_active) values
  ('4cbde0b8-7dee-46bc-ad64-5bc72ba07dc2', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '9ba5f4bb-ee85-49e8-a296-af9ec05a0477', 6900, 10, false),
  ('60935560-61ec-4ad5-add6-19fe79782611', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '81a95eaa-ec46-4ba2-ad37-fecd9484247a', 10900, 20, false),
  ('3af11ebf-d36e-44c2-ab0b-a2a7c72f4b91', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'df802cb2-ddf9-4fad-aeb0-76ae8ddb58cb', 13900, 30, false),
  ('dd2ae1c3-63d9-434a-a078-cccca9e42714', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '476554f2-e6f4-4d5a-a69d-039461bc5751', 6900, 40, false),
  ('b2e95247-c107-4094-a361-bef2c7e8846d', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '52d91c2f-c1be-4147-a7ff-f061a11213b2', 9900, 50, false),
  ('3fda9966-5cb7-4d20-a5af-01bd1bc63bc5', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'd069659d-baac-4e9b-a06a-be91ce21dac9', 10900, 60, false),
  ('5553ab89-6db6-46ac-a742-057ba0a5f5ed', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'a77dbdae-cc3a-46fc-a924-aca59b590410', 10900, 70, false),
  ('d2e78d74-827a-4164-a3f3-f6c3f16607ec', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '0ea897ef-9bde-45d4-a167-f442bc80e68e', 9900, 80, false),
  ('57dcf53d-f44a-45c6-a829-9e8aa909055a', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'ff30cec3-1de8-4575-a351-50a76668bc81', 6900, 90, false),
  ('f24d5fc0-6150-4987-a355-c57905401c68', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'f97f39b1-ded3-481c-a1ae-885091984541', 6900, 100, false),
  ('ed99a301-54a4-46e0-afe6-bc38402fbfb0', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '54b0a3b7-a96f-44cb-a6fc-1765fbca9ed9', 12900, 110, false),
  ('71cb9914-b2eb-4e10-ac98-efeb33b9ab10', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'c02315fc-27f6-41b7-a755-16ab521db373', 6900, 120, false),
  ('2c544f38-42c8-42dd-aa1f-7e281f219f84', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '64f15f33-361b-451c-a4ed-4179735662a3', 10900, 130, false),
  ('b0bee3bc-1e0e-4863-aa06-c09af50e753e', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'ca24ff5a-f35a-4136-a58d-ed0b2d185578', 10900, 140, false),
  ('eae0843a-e082-42bc-a140-ac28310d7495', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'c59857ba-c2c0-4dfb-a9e1-a471c6eb621a', 10900, 150, false),
  ('5a22a43a-d0b7-479b-a5d3-54a5cd6f3166', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '6e290412-f98a-4fa9-a55b-c4123a2ede4a', 13900, 160, false),
  ('1751d9a7-d1a1-4e26-aa2e-3e48ab3646a5', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '8f4e81fe-14f4-4405-ab76-401f251680f1', 10900, 170, false),
  ('1737325d-03e7-4455-aa84-7b42d5036567', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '56aba5d0-d635-4ca5-a7e7-6ae90e8c4f83', 13900, 180, false),
  ('780634eb-63f7-499c-a046-619e7ee60896', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'e6c7b983-711a-42c7-a6c1-f8c074688bd9', 7900, 190, false),
  ('d2791b15-cbe7-40c1-adfd-f13b42c4c4f4', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'be429d49-67dd-40e9-a709-65e3107172c5', 10900, 200, false),
  ('ec13fdb1-e6a5-4874-ae12-e5e72072a66a', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '9275cef8-840d-41a5-afc1-f321f5688a93', 12000, 210, false),
  ('e2989cd4-d890-42a6-a2dc-fb64013f5c1f', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '9ecbfe93-cbd0-4c22-a3e3-2c2334a311ac', 12000, 220, false),
  ('4b3fd707-37d0-4e9c-afae-20a83f5c921d', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '0889579a-1729-47d8-af98-6dfee108c886', 12000, 230, false),
  ('d79afca9-ebca-4d09-a4e6-799d604470a3', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '749f188d-5fef-4e82-a587-4e023eda7720', 10900, 240, false),
  ('6021c001-0283-494c-a849-be748cf95f66', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '92f3aebb-db75-428c-abb0-603faa0e4e60', 12000, 250, false),
  ('4c253f63-6852-4858-a6e5-be6edb1f1159', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '71680f45-adba-4b5e-a60a-7c2b8e6ee844', 12000, 260, false),
  ('d79d8647-0780-480f-a51b-e40fb8a4c059', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'f4853989-b2a7-4841-a517-a99bd5bf7b2d', 12000, 270, false),
  ('04e216bf-32af-4879-a486-771918bbc0b3', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '257bfaf0-1ad1-4edb-a1bf-cc1a67a0d355', 10900, 280, false),
  ('2b40cb02-c270-489e-a96c-66dc8498199c', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '67c4c96a-4ed0-42e3-a801-1a073edff543', 5900, 290, false),
  ('bee9eef8-a9e2-498b-a320-440ab10b257b', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'bef50ee7-e9b3-4702-a1d2-760447dae14a', 10900, 300, false),
  ('75942a6d-bb3c-4edd-a44b-c9d994530d0a', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'e91ffde9-99ef-4ef6-a8ce-d0035570bbc3', 10900, 310, false),
  ('6ac935fe-bc32-47e9-a84f-d4ad17c42b90', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '4a1b9612-c426-49f4-a415-eac8b12ad18a', 10900, 320, false),
  ('b127b6bf-6211-47fb-a4f5-6c0e6986f14c', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'ea6c7701-47e3-49e8-a287-130101806649', 10900, 330, false),
  ('cc52310d-699f-474b-aff1-d8996b962575', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'c75aedc4-c422-4f03-aa89-eeba3c5ff187', 10900, 340, false),
  ('ddaa894e-796a-48dd-a56c-086c8e77e4a8', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'f7ed2183-8f9e-466b-aa7c-ada3b3512793', 10900, 350, false),
  ('df8bd8cb-1546-4d45-a861-f3a8162c2bb2', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '7ff727e6-75e9-419a-a40c-1496a3f53b97', 10900, 360, false),
  ('34a37de6-bce3-447e-a636-f8f8f7b29b78', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '7b6a9487-a8c8-4313-ab59-4775e33b67e1', 10900, 370, false),
  ('fbd62cfa-be03-4030-ad99-b201d1b55f36', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'bd743b4e-99ea-4858-a879-cf359e3abf9a', 12900, 380, false),
  ('ef14fcb5-2e9f-4081-a977-329a6c80805e', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '1ecb1eb0-a3e3-4605-a10c-319356fefa2c', 10900, 390, false),
  ('6317f79f-7c08-4a1c-a68b-f7e4c3717174', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '6a355b36-8c19-4dd7-ae33-038cf14b0f49', 5900, 400, false),
  ('c000fc0c-bc16-4a7e-a8e1-51ac47c2ed63', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'e8da2b16-eed3-4010-af17-f67219a3d87e', 4000, 410, false),
  ('4fc188de-1e8b-4527-a8e2-b9996d2b768a', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '7135dbf4-2182-4ed6-ae6a-2f9afee2c0d3', 10900, 420, false),
  ('7febd225-6438-4826-ab17-8417d4187c8b', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'f2450d69-4bf9-41cc-a489-079b55e619f6', 10900, 430, false),
  ('f8d0102a-d374-4d93-a3a8-3f1285ee05e8', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', 'a2d66075-8a26-44a7-a23e-115287123af7', 12900, 440, false),
  ('db3b0aaf-0dc0-41e2-a201-b401e7c449b6', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '082891cf-f1a4-4fbb-aefb-07d0f8f817f1', 12900, 450, false),
  ('7627ebcf-4082-4265-a343-2198c7346c55', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '3c7fc0ce-c798-4b36-a4a2-b778db302c68', 10900, 460, false),
  ('56e8cb12-e1d2-4551-a562-8162dcc5328e', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '077a8845-034f-4fe4-ac88-7bbd1d3099bb', 10900, 470, false),
  ('a5626a98-4166-4a1a-a26d-315283516450', '098e2390-9b9a-46cd-ae5b-09053780d099', '51115c58-7fe3-4aba-a1a1-5a24d85382f5', 8900, 480, false),
  ('d4199cfd-18ea-48e0-aadf-3272df48252d', '098e2390-9b9a-46cd-ae5b-09053780d099', 'ff30cec3-1de8-4575-a351-50a76668bc81', 8900, 490, false),
  ('3c938838-09a4-4647-a1cf-0b79f449b596', '098e2390-9b9a-46cd-ae5b-09053780d099', '78977f3f-7be5-4902-aa29-196daecd9e78', 8900, 500, false),
  ('faf3d85b-f184-493e-a352-f82fa24270dc', '098e2390-9b9a-46cd-ae5b-09053780d099', '032ffa71-416f-410d-afa4-f0c2c851a37d', 11000, 510, false),
  ('532a752d-3a14-4ec4-a3ea-c7bfd3fb6248', '098e2390-9b9a-46cd-ae5b-09053780d099', 'a3c2e5cf-0c02-4fa1-a033-df385ea00c2e', 7900, 520, false),
  ('e9be02af-6b81-4526-a0c9-653cde1c4325', '098e2390-9b9a-46cd-ae5b-09053780d099', '48e45752-9ad2-4630-a15a-a133a30babee', 9900, 530, false),
  ('52740f32-b754-4b64-ad92-a6c4641eee63', '098e2390-9b9a-46cd-ae5b-09053780d099', '59c2310c-849f-42b1-a817-8715116d8f17', 9900, 540, false),
  ('fe91be51-34c7-41dd-a611-514c1e3348d6', '098e2390-9b9a-46cd-ae5b-09053780d099', '7135dbf4-2182-4ed6-ae6a-2f9afee2c0d3', 8900, 550, false),
  ('d39c5401-a6bc-4cca-ae3d-00b9ae0736e6', '098e2390-9b9a-46cd-ae5b-09053780d099', '4fe69c9a-cc1d-4c70-a682-6ccf740f2c3a', 5900, 560, false),
  ('dbbd83ee-8f55-4fdf-a6f1-5f02b93a1f8a', '098e2390-9b9a-46cd-ae5b-09053780d099', 'fc9fc49f-4f0f-4a25-a86f-b8e2c8932407', 11000, 570, false),
  ('6604ec67-b95c-49cc-ac19-faa7569ad275', '098e2390-9b9a-46cd-ae5b-09053780d099', '55f3fbad-f01f-42c8-a17f-e9e28341f10b', 11000, 580, false),
  ('e2e5e8a4-cd45-4025-a467-bf2504fda62e', '098e2390-9b9a-46cd-ae5b-09053780d099', 'd8552969-86e3-4166-a484-d67314744c9d', 8900, 590, false),
  ('4180f020-065f-4606-ade3-4263333b477a', '098e2390-9b9a-46cd-ae5b-09053780d099', '249d5eea-bb21-4555-ab1a-9fb74911a4cf', 5900, 600, false),
  ('3387ba06-1779-4147-aafe-65fede0e6a23', '098e2390-9b9a-46cd-ae5b-09053780d099', '5786123a-6435-4f32-a199-c966998b3c10', 13000, 610, false),
  ('f8697d25-66cb-4d8c-aa29-b161f0e506e7', '098e2390-9b9a-46cd-ae5b-09053780d099', '2bcc8895-c2e7-4adf-a8fe-428981089cd5', 9900, 620, false),
  ('99a8ea05-539b-465f-a2f3-dde1cda1f602', '098e2390-9b9a-46cd-ae5b-09053780d099', 'ca4c954e-c784-4484-a764-dd91d85921e6', 9900, 630, false),
  ('f784fe81-8288-4604-a649-e2ec8f00ceb0', '098e2390-9b9a-46cd-ae5b-09053780d099', '7ff727e6-75e9-419a-a40c-1496a3f53b97', 9900, 640, false),
  ('99297b37-dec3-4939-ab6a-4acb3665e6a4', '098e2390-9b9a-46cd-ae5b-09053780d099', '974feb0c-0649-4a60-a05f-fe36afa40e70', 9900, 650, false),
  ('2e716a90-cc02-4732-afa6-b93d9c90be7f', '098e2390-9b9a-46cd-ae5b-09053780d099', '3118e713-773c-4201-a5e1-826edaf788bf', 11000, 660, false),
  ('65a87e8f-6e6f-4551-aaff-859799e5a516', '098e2390-9b9a-46cd-ae5b-09053780d099', '18cb9677-0f79-452a-a267-37955597979b', 11000, 670, false),
  ('b4b0233d-74ec-42b3-a2d2-5d6d615c124a', '098e2390-9b9a-46cd-ae5b-09053780d099', 'b71f4b14-ec16-4675-a2ea-70880c6a3fa4', 4900, 680, false),
  ('c68902fb-5385-4efa-acea-ffcf9cee464b', '098e2390-9b9a-46cd-ae5b-09053780d099', 'a2da0e85-574c-4846-ac0a-2bb994f4996c', 11000, 690, false),
  ('86e54b3d-4756-4c26-a5a3-7a3c65dfad19', '098e2390-9b9a-46cd-ae5b-09053780d099', '8b4d2880-9d4a-425c-a350-84d13e3e5a7a', 6900, 700, false),
  ('b2301e52-8f9a-4538-a5a1-f6e11a403452', '098e2390-9b9a-46cd-ae5b-09053780d099', '07dac96a-2696-4bb1-a58b-0267dad3a20f', 5900, 710, false),
  ('36c545ea-b3e2-4e7f-a563-1cf2dab09341', '098e2390-9b9a-46cd-ae5b-09053780d099', 'fcf5f7ef-4ba2-4fb3-adcd-6e5aa9856a6c', 11000, 720, false),
  ('c9cb306f-6b88-4c2c-a191-21664f222253', '098e2390-9b9a-46cd-ae5b-09053780d099', '5545b7fa-ebc5-4b08-abc0-766b459b9407', 10000, 730, false),
  ('7341ec1b-5c3a-4f0f-a40d-63b1a7f0a91a', '098e2390-9b9a-46cd-ae5b-09053780d099', '1ecb1eb0-a3e3-4605-a10c-319356fefa2c', 9900, 740, false),
  ('4436b8df-99a2-45a5-ae63-86f63f94b2cb', '098e2390-9b9a-46cd-ae5b-09053780d099', '09456bbd-a4af-4745-a4b7-0e8372dc4a18', 7900, 750, false),
  ('f598c3e1-3be9-46cf-a3f7-1608f27324b1', '098e2390-9b9a-46cd-ae5b-09053780d099', '4d2e14b8-9672-4a9d-a1ee-a2c07d6e5213', 11000, 760, false),
  ('ecfdb6f6-92d4-4aa2-a589-77124c6ac471', '098e2390-9b9a-46cd-ae5b-09053780d099', 'feeef41f-7f46-4f82-aedb-03d2f5da9b28', 9900, 770, false),
  ('ae70392f-4c87-43f8-a399-10bcc29f32df', '098e2390-9b9a-46cd-ae5b-09053780d099', '34e0b082-3d7f-4f6b-aca7-a9506b786feb', 6900, 780, false),
  ('08aeafad-213c-4e8a-a19c-bac7b6251a93', '098e2390-9b9a-46cd-ae5b-09053780d099', 'a6cbc529-c379-4d80-a38b-30ea4fe43c6f', 11000, 790, false),
  ('704a8736-e45f-4b49-ab66-5ba1d0a32046', '098e2390-9b9a-46cd-ae5b-09053780d099', '5ff51909-1a40-4e86-a006-eb57160a78f2', 9900, 800, false),
  ('19136b79-060c-45a3-a9ec-e6632ebbf7cc', '098e2390-9b9a-46cd-ae5b-09053780d099', '630bd35a-da35-483a-ab12-69164b9fe84f', 11000, 810, false),
  ('312f274b-6d56-481d-aed4-ddb79f3d7520', '098e2390-9b9a-46cd-ae5b-09053780d099', '1b285863-ae69-4bcf-af8d-7a8544e037e3', 6000, 820, false),
  ('4167abb0-c7f9-4386-a321-cf922560abb8', '098e2390-9b9a-46cd-ae5b-09053780d099', '5886a511-7755-4077-a18d-61a913825080', 10000, 830, false)
on conflict (id) do nothing;

-- How to finish, once the dishes carry a food type (`E16-52`):
--
--   update menu_item mi set is_active = true
--     from dish d where d.id = mi.dish_id and d.food_type is not null;
--
-- It is deliberately NOT run here. Activating is the moment a dish becomes visible to a
-- parent, and that should be a thing somebody does on purpose after checking the marks —
-- not a side effect of seeding. The statement is idempotent and safe to re-run.

-- Which school eats from which menu. Straight from School-Menu, which is the flag Bubble
-- actually gates on.
insert into menu_assignment (id, school_id, menu_id, valid_from, valid_to) values
  ('943b5f6b-0c15-4f39-a351-e7f6ebfcb6b4', '77308e75-d8e9-47ba-a503-7c38d482a72c', '2ff90ad6-0d28-4fa4-aebb-7892c3999c20', '2025-10-16', null),
  ('a63239ee-fbac-4261-a2ee-bfd194ad2004', '79752fe3-841f-45b6-a47b-1169ce70e648', '098e2390-9b9a-46cd-ae5b-09053780d099', '2025-10-16', null),
  ('feb0e51c-3050-454d-ad88-c4d46c91c4cf', '50994394-8557-4985-a76f-707d16a83c1a', '098e2390-9b9a-46cd-ae5b-09053780d099', '2026-05-22', null)
on conflict (id) do nothing;

-- Cutoff. Without a kitchen_config row the cutoff functions have nothing to read and every
-- service date reads as closed, which looks exactly like a bug (ux-spec §5.21 N2).
insert into kitchen_config (kitchen_id, order_cutoff_time) values ('35ec28ed-71df-4592-a7d0-32b62d5df354', '21:00:00')
on conflict (kitchen_id) do nothing;

insert into school_config (school_id, default_delivery_mode, allow_classroom_delivery) values
  ('77308e75-d8e9-47ba-a503-7c38d482a72c', 'classroom', true),
  ('50994394-8557-4985-a76f-707d16a83c1a', 'classroom', true),
  ('79752fe3-841f-45b6-a47b-1169ce70e648', 'classroom', true)
on conflict (school_id) do nothing;

-- Hide the synthetic schools now that real ones exist. By id, never a bare update (E05-21),
-- and deactivated rather than deleted so the E05-16 test order keeps its references.
update school set is_active = false, updated_at = now() where id in (
  '50000000-0000-0000-0000-000000000001',  -- Alpha Public School
  '50000000-0000-0000-0000-000000000002',  -- Bravo International
  '50000000-0000-0000-0000-000000000003'   -- Cedar Valley
);

-- Same for their menus, so no assignment can resolve to a fixture dish.
update menu set status = 'retired' where id in (
  'e0000000-0000-0000-0000-000000000001',
  'e0000000-0000-0000-0000-000000000002',
  'e0000000-0000-0000-0000-000000000003'
);

commit;
