// GENERATED by scripts/build-company-identity.mjs from docs/legal/company.json.
// Do not edit. Change the JSON and re-run; `--check` runs in the smoke test.
//
// It exists because the app cannot import from docs/ — .easignore excludes that directory
// from the EAS upload, and the mobile bundle died resolving it. See the script header.
export const COMPANY_JSON = {
  "_comment": [
    "The company's published identity — ONE source, read by every document that states it (E12-25).",
    "JSON rather than TypeScript so a plain .mjs script can read it too: the website renderer, the",
    "app's generated policy documents and the placeholder register all substitute from this file,",
    "and a value that lives in only one of them is the drift this file exists to prevent.",
    "null means genuinely unknown. It is never substituted, so its «TOKEN» survives into the",
    "rendered document and a production build refuses to publish it."
  ],
  "legalName": "GRAYBAG SOLUTIONS PRIVATE LIMITED",
  "registeredAddress": "SCO-461-462, Top Floor, Sector 35-C, Chandigarh, 160022",
  "gstin": "03AAMCG3438M1ZD",
  "sacCode": null,
  "signatureTreatment": null,
  "supportEmail": "support@graybag.com",
  "jurisdictionCity": "SAS Nagar (Mohali), India",
  "grievanceOfficer": {
    "name": null,
    "title": "Grievance Officer, GrayBag Solutions Private Limited",
    "email": "support@graybag.com",
    "address": null,
    "_comment": "name is deliberately NULL and title names the OFFICE, not a person. Andy, 2026-08-15: no individual's name in the app, and every route to a person goes to support@graybag.com. Privacy notice version 3 publishes exactly this. It previously read Vivek / vivek@graybag.com, and leaving that here would have been a second source of truth that reintroduces the name the first time anybody wires the grievance block from this file. WHETHER DPDP REQUIRES A NATURAL PERSON IS OPEN and is E20-52 / E20-01 — if the lawyer says it does, a name comes back here and in notice version 4."
  },
  "_effectiveDates": "Fixed, never computed. An effective date that moves with each build is not an effective date.",
  "termsEffectiveDate": "2026-08-14",
  "_supportEmailComment": "Was info@graybag.com. The app routes every support and grievance action to support@graybag.com (E20-51), and the published privacy notice says the same, so this is the third place that had to agree. info@graybag.com still appears in privacy policy §7 and §8, which are LAWYER-APPROVED BASELINE TEXT and are not edited here — changing them is a notice version and belongs with E20-01."
} as const;
