/**
 * Gradle daemon memory. `E14-36`.
 *
 * # The failure this fixes
 *
 * The `Maestro (cart)` CI job spent **45 minutes and then timed out**, on every pull request, in
 * "Build the staging APK". It was not slow. The log is thousands of repetitions of:
 *
 *     Exception in thread "RMI TCP Connection(idle)" java.lang.OutOfMemoryError: Metaspace
 *
 * The Gradle daemon exhausts its metaspace, and then neither finishes nor dies: it thrashes,
 * throwing and continuing, until the job's own timeout kills it. **A build that fails takes 45
 * minutes to say so**, which is the expensive shape — a hard failure at four minutes would have
 * been diagnosed the first time anyone saw it.
 *
 * Metaspace holds loaded class metadata, and it is separate from the heap: raising `-Xmx` does
 * nothing for it, which is why the usual "give Gradle more memory" advice misses. A React Native
 * app's build loads an enormous number of classes — every autolinked native module contributes
 * Kotlin and Java compilation — so the ceiling is reached by adding dependencies, not by writing
 * more application code. That is why nobody changed anything to cause this.
 *
 * # Why a config plugin rather than a line in the CI workflow
 *
 * `android/` is generated by `expo prebuild` and is not committed, so any edit to
 * `gradle.properties` is erased on every build. A workflow-only fix would also apply **only** to
 * CI — and EAS builds run the same Gradle on the same generated project. Fixing it here means the
 * two cannot disagree about how much memory the build gets, which is the sort of divergence that
 * produces "works on EAS, times out in CI" and a day spent on the wrong difference.
 */
const { withGradleProperties } = require('expo/config-plugins')

/**
 * `-Xmx` is the heap; `MaxMetaspaceSize` is the one that was actually exhausted.
 *
 * Expo's template ships `-Xmx2048m -XX:MaxMetaspaceSize=512m` — verified by running `prebuild`
 * with this plugin removed, not read from documentation. So this doubles the heap and gives the
 * metaspace that actually ran out **four times** what it had.
 *
 * Four rather than two because this job has never once passed, so the cheap thing is to clear it
 * by a margin and tighten later if we ever care — not to spend a CI round trip discovering that
 * 1024m was also short. 6 GB total on a 16 GB runner is not a constraint worth optimising.
 *
 * Sized for a GitHub `ubuntu-latest` runner (4 vCPU, 16 GB), leaving ample room for the Kotlin
 * compile daemon, which is a separate JVM and is *not* covered by these numbers. Going higher
 * risks the runner's OOM killer taking the whole job, which fails in a way that looks nothing
 * like this and would send the next person somewhere else entirely.
 *
 * **`ExitOnOutOfMemoryError` is the half that bounds the damage**, and it matters more than the
 * numbers. More memory is a guess about how much is enough; this is a guarantee about what
 * happens when the guess is wrong. Without it the daemon caught the error and carried on, so the
 * build neither finished nor failed and burned the job's full 45-minute timeout — turning a
 * diagnosable crash into a mystery hang. With it, the same exhaustion kills the JVM at once and
 * CI reports a build failure in minutes, with the reason in the log.
 */
const JVM_ARGS = '-Xmx4096m -XX:MaxMetaspaceSize=2048m -XX:+ExitOnOutOfMemoryError'

/** Gradle properties this plugin owns. Anything else in the file is left alone. */
const MANAGED = {
  'org.gradle.jvmargs': JVM_ARGS,
}

/**
 * The transform, pure so it can be tested without Expo's mod pipeline — the same reason
 * `withUpiQueries` splits `applyUpiQueries` out. `withGradleProperties` only registers a
 * callback, so a test that calls the plugin and inspects the result asserts nothing.
 *
 * Expo models the file as an array of `{ type: 'property' | 'comment', key, value }`. Existing
 * keys are **replaced in place** rather than appended: Gradle takes the last occurrence of a
 * duplicated key, so appending would work by accident and read as though it did not.
 */
function applyGradleMemory(properties) {
  const next = Array.isArray(properties) ? [...properties] : []

  for (const [key, value] of Object.entries(MANAGED)) {
    const existing = next.findIndex((item) => item.type === 'property' && item.key === key)
    if (existing >= 0) next[existing] = { type: 'property', key, value }
    else next.push({ type: 'property', key, value })
  }

  return next
}

module.exports = function withGradleMemory(config) {
  return withGradleProperties(config, (cfg) => {
    cfg.modResults = applyGradleMemory(cfg.modResults)
    return cfg
  })
}

module.exports.JVM_ARGS = JVM_ARGS
module.exports.applyGradleMemory = applyGradleMemory
